# .gitlab-ci.yml
# rust-secp256k1


stages:
  - test
  - build



image:                             tetcoin/rust-builder:latest

variables:
  GIT_STRATEGY:                    fetch
  GIT_SUBMODULE_STRATEGY:          recursive
  CARGO_HOME:                      "/ci-cache/${CI_PROJECT_NAME}/cargo/${CI_JOB_NAME}"
  SCCACHE_DIR:                     "/ci-cache/${CI_PROJECT_NAME}/sccache"
  CI_SERVER_NAME:                  "GitLab CI"
  DOCKER_OS:                       "debian:stretch"
  ARCH:                            "x86_64"



.docker-env:                       &docker-env
  tags:
    - linux-docker

.compiler_info:                    &compiler_info
  before_script:
    - rustup show
    - cargo --version
    - sccache -s

.build-refs:                       &build-refs
  only:
    - master
    - schedules
    - web
    - /^v[0-9]+\.[0-9]+.*$/        # i.e. v1.0, v2.1rc1

.test-refs:                        &test-refs
  only:
    - master
    - schedules
    - web
    - /^v[0-9]+\.[0-9]+.*$/        # i.e. v1.0, v2.1rc1
    - /^[0-9]+$/





test-linux-stable:                 &test
  stage:                           test
  <<:                              *test-refs
  <<:                              *docker-env
  <<:                              *compiler_info
  variables:
    RUST_TOOLCHAIN: stable
    RUSTFLAGS: -Cdebug-assertions=y
    TARGET: native
  script:
    - time cargo test --all --release --verbose
    - sccache -s




build-linux-release:               &build
  stage:                           build
  <<:                              *build-refs
  <<:                              *docker-env
  <<:                              *compiler_info
  script:
    - time cargo build --release --verbose
    - sccache -s



