[package]
name = "tetsy-secp256k1"
version = "0.7.0"
authors = [
  "Dawid Ciężarkiewicz <dpc@ucore.info>",
  "Andrew Poelstra <apoelstra@wpsoftware.net>",
  "Parity Technologies <admin@parity.io>",
]
license = "CC0-1.0"
homepage = "https://github.com/tetcoin/tetsy-secp256k1/"
repository = "https://github.com/tetcoin/tetsy-secp256k1/"
documentation = "https://www.wpsoftware.net/rustdoc/secp256k1/"
description = "Fork of Rust bindings for Pieter Wuille's `libsecp256k1` library. Implements ECDSA for the SECG elliptic curve group secp256k1 and related utilities."
keywords = [ "ECDSA", "secp256k1", "libsecp256k1", "bitcoin", "vapory" ]
readme = "README.md"
build = "build.rs"

[build-dependencies]
cc = "1.0.45"
cfg-if = "0.1.10"

[lib]
name = "secp256k1"
path = "src/lib.rs"

[features]
unstable = []
default = []
dev = ["clippy"]

[dependencies]
arrayvec = "0.5.1"
clippy = { version = "0.0.302", optional = true }
rand = "0.7.2"

[dev-dependencies]
hex-literal = "0.2.1"
rand_core = "0.5.1"
